//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_End_Of_PWI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_End_Of_PWI.App_LocalResources._Layout.cshtml", typeof(_Layout_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mnie.
        /// </summary>
        public static string AboutPL {
            get {
                return ResourceManager.GetString("AboutPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will speak to you soon!!.
        /// </summary>
        public static string communicat {
            get {
                return ResourceManager.GetString("communicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wkrótce się odezwę.
        /// </summary>
        public static string communicatPL {
            get {
                return ResourceManager.GetString("communicatPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string ContactPl {
            get {
                return ResourceManager.GetString("ContactPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum is simply a fictitious text of the printing industry and composition. Lorem ipsum is standard manikin text in the industry since 1500, when an unknown printer took a type gallery and scramble to create a type book. It survived not only five centuries, but also a leap to the electronic composition, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing fragments of lorem ipsum, and more recently with computer publishing software such as Ald [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum is simply a fictitious text of the printing industry and composition..
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum to po prostu fikcyjny tekst branży drukarskiej i składu..
        /// </summary>
        public static string Description1PL {
            get {
                return ResourceManager.GetString("Description1PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum is a standard dummy text in the industry since 1500.
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum jest standardowym tekstem manekina w branży od 1500 roku.
        /// </summary>
        public static string Description2PL {
            get {
                return ResourceManager.GetString("Description2PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when an unknown printer took a type gallery and scrambled to create a type book..
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kiedy nieznana drukarka wzięła galerię typu i gramoliła się, aby stworzyć książkę z typami..
        /// </summary>
        public static string Description3PL {
            get {
                return ResourceManager.GetString("Description3PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum to po prostu fikcyjny tekst branży drukarskiej i składu. Lorem ipsum jest standardowym tekstem manekina w branży od 1500 roku, kiedy nieznana drukarka wzięła galerię typu i gramoliła się, aby stworzyć książkę z typami. Przetrwał nie tylko pięć wieków, ale także skok do składu elektronicznego, pozostając zasadniczo niezmieniony. Został spopularyzowany w latach sześćdziesiątych wraz z wydaniem arkuszy Letraset zawierających fragmenty lorem ipsum, a ostatnio z oprogramowaniem do publikowania na kom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionPL {
            get {
                return ResourceManager.GetString("DescriptionPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Me.
        /// </summary>
        public static string Find_Me {
            get {
                return ResourceManager.GetString("Find Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znajdź mnie.
        /// </summary>
        public static string Find_MePL {
            get {
                return ResourceManager.GetString("Find MePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave contact details.
        /// </summary>
        public static string GetContact {
            get {
                return ResourceManager.GetString("GetContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostaw dane kontakowe.
        /// </summary>
        public static string GetContactPL {
            get {
                return ResourceManager.GetString("GetContactPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string NamePL {
            get {
                return ResourceManager.GetString("NamePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        public static string PhonePL {
            get {
                return ResourceManager.GetString("PhonePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string RegisterPL {
            get {
                return ResourceManager.GetString("RegisterPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value!.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe dane.
        /// </summary>
        public static string valuePL {
            get {
                return ResourceManager.GetString("valuePL", resourceCulture);
            }
        }
    }
}
